### ISSUE TITLE
Silently does not work

### ISSUE THREAD

**Issue by neopaf** [miguelcordovam/intellij_plugins#4]
plugin v1.4

IntelliJ IDEA 2017.3.4 (Community Edition)
Build #IC-173.4548.28, built on January 30, 2018
JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.3

```
2018-03-16 12:00:13,307 [  99123]  ERROR - intellij.openapi.progress.Task - No enum constant com.restdocs.action.common.HttpMethod.CANNOTCONVERTEXPRESSION 
java.lang.IllegalArgumentException: No enum constant com.restdocs.action.common.HttpMethod.CANNOTCONVERTEXPRESSION
        at java.lang.Enum.valueOf(Enum.java:238)
        at com.restdocs.action.common.HttpMethod.valueOf(HttpMethod.java:3)
        at com.restdocs.action.util.ServicesUtil.getHttpMethod(ServicesUtil.java:177)
        at com.restdocs.action.util.ServicesUtil.createRestServices(ServicesUtil.java:157)
        at com.restdocs.action.util.ServicesUtil.access$200(ServicesUtil.java:25)
        at com.restdocs.action.util.ServicesUtil$1.run(ServicesUtil.java:104)
        at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:912)
        at com.restdocs.action.util.ServicesUtil.getAllServicesByModule(ServicesUtil.java:84)
        at com.restdocs.toolwindow.RestServicesController.loadServices(RestServicesController.java:40)
        at com.restdocs.toolwindow.RestServicesController.init(RestServicesController.java:34)
        at com.restdocs.action.ShowRestServicesAction$1.run(ShowRestServicesAction.java:48)
        at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:713)
```

**Comment by lukasMega** [comment]
plugin v1.4

IntelliJ IDEA 2018.1.1 EAP (Ultimate Edition)
Build #IU-181.4445.4, built on March 29, 2018
JRE: 1.8.0_152-release-1136-b27 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6

 Last Action: ShowRestServices 

```
2018-04-03 10:53:45,098 [ 157178]  ERROR - intellij.openapi.progress.Task - No enum constant com.restdocs.action.common.HttpMethod.HEAD 
java.lang.IllegalArgumentException: No enum constant com.restdocs.action.common.HttpMethod.HEAD
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.restdocs.action.common.HttpMethod.valueOf(HttpMethod.java:3)
	at com.restdocs.action.util.ServicesUtil.getHttpMethod(ServicesUtil.java:177)
	at com.restdocs.action.util.ServicesUtil.createRestServices(ServicesUtil.java:157)
	at com.restdocs.action.util.ServicesUtil.access$200(ServicesUtil.java:25)
	at com.restdocs.action.util.ServicesUtil$1.run(ServicesUtil.java:104)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:902)
	at com.restdocs.action.util.ServicesUtil.getAllServicesByModule(ServicesUtil.java:84)
	at com.restdocs.toolwindow.RestServicesController.loadServices(RestServicesController.java:40)
	at com.restdocs.toolwindow.RestServicesController.init(RestServicesController.java:34)
	at com.restdocs.action.ShowRestServicesAction$1.run(ShowRestServicesAction.java:48)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
